spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

server:
  port: 8918