### Create
POST http://localhost:8918/awesome-bank-api/expense
Content-Type: application/json

{
  "name": "Habbibs",
  "description": "Jantar no Habbibs",
  "dateTime": "2022-09-30T00:00:00.000+03:00",
  "value": "89.76",
  "tags": [
    "COMIDA",
    "LAZER"
  ]
}

<> 2022-09-23T085307.404.json

### FindById
GET http://localhost:8918/awesome-bank-api/expense/1fbb1701-4572-4438-87e0-d8f3b397457b

### FindAll
GET http://localhost:8918/awesome-bank-api/expense